DROP TABLE IF EXISTS department;

DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS employee;

CREATE TABLE department (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    department_name VARCHAR(30)
);

CREATE TABLE roles (
    roleid INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    title VARCHAR(30) NOT NULL UNIQUE,
    salary DECIMAL,
    department_id INTEGER/*,
    CONSTRAINT fk_dept FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL*/
);

CREATE TABLE employee (
    employid INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE SET NULL,
    manager_id INTEGER
);